package io.github.ibcmanager.model;

public enum RuntimeState {
    STOPPED,
    VALIDATING,
    STARTING,
    STARTUP_STALLED,
    AUTO_RECOVERY_STOPPING,
    AUTO_RECOVERY_FORCE_CLEANUP,
    AUTO_RECOVERY_COOLDOWN,
    STARTING_FRESH,
    RECOVERY_FAILED,
    RESTARTING,
    WAITING_FOR_LOGIN,
    WAITING_FOR_SECOND_FACTOR,
    RUNNING,
    API_LISTENER_DETECTED,
    PAUSING,
    PAUSED,
    STOPPING,
    ERROR,
    UNKNOWN
}
